; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = Webserver_DigitalWrite_Example

[env:esp32dev]
platform = espressif32@~6.0.0
board = esp32-s3-devkitc-1
framework = arduino
build_flags =
        -DARDUINO_ESP32S3_DEV
        ; -DARDUINO_VARIANT="esp32s3"
        -DLOG_LEVEL=LOG_LEVEL_VERBOSE
        -DCORE_DEBUG_LEVEL=5
        -DCONFIG_ARDUHAL_LOG_COLORS=1
        -D__PATH__=\"$PROJECT_DIR\"
        -D WIFI_SSID='"Charlie"'
        -D WIFI_PASS='"logu9769"'

upload_port= COM14
monitor_port=COM14
monitor_speed=115200
monitor_filters = direct, esp32_exception_decoder, time, log2file


lib_deps= 
        fastled/FastLED@3.7.1
        adafruit/Adafruit GFX Library
        adafruit/Adafruit SSD1306
        adafruit/Adafruit Unified Sensor
        adafruit/Adafruit BMP280 Library
        knolleary/PubSubClient
